#!/usr/bin/env lua
local input = assert(...)
local tl = require("tl")
local res = assert(tl.process(input))
local esc = string.char(27) .. "["
local function report_errors(color, category, errors)
	if #errors == 0 then return end
	for _, e in ipairs(errors) do
		io.stderr:write(esc, color, ";1m", category, esc, "0m:", e.filename, ":", e.y, ":", e.x, ": ", (e.msg or ""), "\n")
	end
	os.exit(1)
end
report_errors(31, "syntax", res.syntax_errors)
report_errors(37, "unknown", res.unknowns)
report_errors(36, "type", res.type_errors)
